"""Package princess/princess.html's <svg> into princess/princess.js (window.PrincessArt)
so canvas scenes (aurora.bg.js) can inject it with a <script> tag and rasterize it.

    python c:/Code/subtraction_game/backgrounds/princess/_pack_princess.py

Re-run after editing the SVG in princess.html. Besides minifying, this moves the
LEFT HAND's three polygons (drawn inside the Hips group in the original pen) into
the Left_Arm group, so a transform on Left_Arm rotates the whole arm — palm
included — when the scene builds pose frames (the raised arm of the cast).
"""
import json, re
from pathlib import Path

HERE = Path(__file__).parent
html = (HERE / 'princess.html').read_text(encoding='utf-8')
m = re.search(r'<svg[\s\S]*?</svg>', html)
assert m, 'no <svg> in princess.html'
svg = re.sub(r'\s+', ' ', m.group(0)).replace('> <', '><').strip()

# the left hand: the palm, its top and its shading — move them into Left_Arm
hand_parts = [
    r'<path fill="#F8E8DC" d="M191\.4,432[^>]*>',
    r'<path fill="#FBF0E9" d="M215\.7,394\.1[^>]*>',
    r'<polyline fill="#EBD7CC" points="236\.6,396\.7[^>]*>',
]
moved = []
for pat in hand_parts:
    mm = re.search(pat, svg)
    assert mm, 'hand part not found: ' + pat
    moved.append(mm.group(0))
    svg = svg.replace(mm.group(0), '', 1)
arm_open = svg.index('<g id="Left_Arm">')
arm_close = svg.index('</g>', arm_open)
svg = svg[:arm_close] + ''.join(moved) + svg[arm_close:]

js = ('/* ── princess/princess.js — the low-poly PRINCESS art, packaged for canvas scenes ──\n'
      '   GENERATED by princess/_pack_princess.py from princess/princess.html (Flat\n'
      '   Kingdom paper-art style; original pen by acupajoe.io) — edit the SVG there\n'
      '   and re-run the script. One minified string so a background module can\n'
      '   inject this file with a <script> tag (file:// safe) and rasterize the SVG\n'
      '   through an <img> data URL. Groups keep their ids (Dress, Legs, Hips, Chest,\n'
      '   Left_Arm, Head, Hair_Back, Hair_Front, Tiara, Face…), so a scene can build\n'
      '   pose frames by injecting transform="…" into a group tag; the left hand\'s\n'
      '   polygons were moved INTO Left_Arm so the palm travels with the arm.\n'
      '   viewBox 0 0 612 792; the figure spans x≈186–402, y≈6–757, feet on y≈757;\n'
      '   the left arm hangs from the shoulder ≈ (238,256) to the palm ≈ (212,412).\n'
      '       window.PrincessArt = { svg, viewBox, bbox, feetY, centerX, shoulder, palm }\n'
      '   Used by aurora.bg.js. */\n'
      'window.PrincessArt = {\n'
      '  svg: ' + json.dumps(svg) + ',\n'
      '  viewBox: [0, 0, 612, 792],\n'
      '  bbox: { x0: 186, y0: 6, x1: 402, y1: 757 },\n'
      '  feetY: 757, centerX: 294,\n'
      '  shoulder: [238, 256], palm: [212, 412],\n'
      '};\n')
(HERE / 'princess.js').write_text(js, encoding='utf-8')
print('princess.js written:', len(svg), 'svg chars, hand parts moved:', len(moved))
